# Generated by Django 5.2.5 on 2025-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
